services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: apptest-backend
    privileged: true
    cap_add:
      - NET_BIND_SERVICE
      - SYS_ADMIN
    devices:
      - /dev/kvm:/dev/kvm
    ports:
      - "3001:3001"
      - "8000:8000"
      - "5037:5037"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - CORS_ALLOWED_ORIGINS=*
      - AVD_NAME=autoapp-local
      - WS_SCRCPY_PORT=${WS_SCRCPY_PORT:-8000}
      - WS_SCRCPY_PLAYER=${WS_SCRCPY_PLAYER:-webcodecs}
      - EMULATOR_CONSOLE_PORT=5554
      - EMULATOR_ADB_PORT=5555
      - ADB_SERVER_PORT=5555
      - ANDROID_ADB_SERVER_PORT=5555
      - ADB_SERVER_SOCKET=tcp:0.0.0.0:5555
    volumes:
      - android-avd:/opt/android-sdk/avd
      - ./var/autoapp:/var/autoapp  # Mount app library and logs
    networks:
      - apptest-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: apptest-frontend
    ports:
      - "5173:80"
    networks:
      - apptest-network
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  android-avd:

networks:
  apptest-network:
    driver: bridge
