services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: apptest-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - CORS_ALLOWED_ORIGINS=*
      - EXTERNAL_EMULATOR=true
      # Discovery System Configuration
      - ENABLE_DISCOVERY=true
      - DISCOVERY_PANEL=true
      - GPS_PANEL=false
      - GRAPH_PATH=/app/data/graph.json
      - SESSIONS_DIR=/app/data/sessions
      - SCREENSHOTS_DIR=/app/data/screenshots
      - ADB_HOST=host.docker.internal
      - ANDROID_SERIAL=emulator-5554
      - SNAPSHOT_TIMEOUT_MS=5000
      - UIXML_TMP=/tmp/view.xml
      - MERGE_THRESHOLD=0.9
      - EXTERNAL_EMULATOR_HOST=${EXTERNAL_EMULATOR_HOST:-host.docker.internal}
      - EXTERNAL_EMULATOR_ADB_PORT=${EXTERNAL_EMULATOR_ADB_PORT:-5555}
      - EMULATOR_GRPC_ENDPOINT=${EMULATOR_GRPC_ENDPOINT:-http://envoy:8080}
      - EMULATOR_WEBRTC_PUBLIC_URL=${EMULATOR_WEBRTC_PUBLIC_URL:-http://82.165.175.97:9000}
      - EMULATOR_WEBRTC_ICE_SERVERS=${EMULATOR_WEBRTC_ICE_SERVERS:-stun:stun.l.google.com:19302,stun:stun1.l.google.com:19302}
    volumes:
      - ./var/autoapp:/var/autoapp  # Mount app library and logs
      - emulator-home:/root/.android  # Share ADB keys with emulator
      - discovery-data:/app/data  # Discovery artifacts storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - apptest-network
    restart: unless-stopped

  emulator:
    image: us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:30.1.2
    container_name: apptest-emulator
    network_mode: host
    devices:
      - /dev/kvm:/dev/kvm
    environment:
      - AVD_CONFIG=hw.cpu.ncore=4
      - ADBKEY=${ADBKEY:-}  # ADB key will be read from shared volume
      - WEBRTC_PORT_RANGE=53000-53100
    volumes:
      - emulator-home:/root  # Share ADB keys AND console auth token
    shm_size: 1g
    restart: unless-stopped

  envoy:
    image: envoyproxy/envoy:v1.30-latest
    container_name: apptest-envoy
    depends_on:
      - emulator
    volumes:
      - ./infra/envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "9000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - apptest-network
    restart: unless-stopped

  gpsd:
    image: python:3.11-alpine
    container_name: apptest-gpsd
    network_mode: host
    restart: unless-stopped
    environment:
      - ADB_SERVER_HOST=127.0.0.1
      - ADB_SERVER_PORT=5037
    volumes:
      - ./scripts/gpsd_server.py:/opt/gpsd/server.py:ro
      - emulator-home:/root:ro  # read the same console token
    command: |
      sh -lc "
        apk add --no-cache android-tools curl >/dev/null &&
        python /opt/gpsd/server.py
      "
    depends_on:
      - emulator

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: apptest-frontend
    ports:
      - "5173:80"
    networks:
      - apptest-network
    restart: unless-stopped
    depends_on:
      - backend

networks:
  apptest-network:
    driver: bridge

volumes:
  emulator-home:  # Shared volume for ADB keys and console auth token
  discovery-data:  # Discovery artifacts storage
