services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: apptest-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - CORS_ALLOWED_ORIGINS=*
      - EXTERNAL_EMULATOR=true
      - WS_SCRCPY_HOST=${WS_SCRCPY_HOST:-host.docker.internal}
      - WS_SCRCPY_PORT=${WS_SCRCPY_PORT:-8000}
      - WS_SCRCPY_PLAYER=${WS_SCRCPY_PLAYER:-mse}
      - EMULATOR_SERIAL=${EMULATOR_SERIAL:-emulator-5554}
    volumes:
      - android-data:/opt/android-sdk
    networks:
      - apptest-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: apptest-frontend
    ports:
      - "5173:80"
    networks:
      - apptest-network
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  android-data:

networks:
  apptest-network:
    driver: bridge
