# Traefik Static Configuration
# AutoApp UI Map & Intelligent Flow Engine

# Global configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# API and Dashboard configuration
api:
  dashboard: true
  insecure: true  # Only for development - secure in production

# EntryPoints configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      middlewares:
        - security-headers@file
        - cors-headers@file

  # WebSocket support for WebRTC streaming
  websocket:
    address: ":8080"

# Providers configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false  # Security: only expose containers with labels
    network: apptest-network

  file:
    directory: /etc/traefik/dynamic
    watch: true

# Log configuration
log:
  level: INFO
  format: json

accessLog:
  format: json
  bufferingSize: 100
  filters:
    statusCodes:
      - "400-499"
      - "500-599"

# Certificate management (Let's Encrypt for production)
certificatesResolvers:
  letsencrypt:
    acme:
      email: "admin@yourdomain.com"  # Update with actual email
      storage: "/etc/traefik/acme/acme.json"
      httpChallenge:
        entryPoint: web

# Ping configuration for health checks
ping:
  entryPoint: "web"

# Metrics and monitoring
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    manualRouting: true